[main]
api_key = "qg8sMtm4170sTRZHHgbPVQ"
access_token = "ce40069ffe95ecafbfb0ad2a72fdee0d"
api_url = "http://192.168.88.216:5002"
storage_server_type = "ipfs server"

[web-server]
host = "https://nbai.io"
port = 443
path = "/download"

[ipfs-server]
gateway_address = "/ip4/127.0.0.1/tcp/8080"

[sender]
bid_mode = 1
offline_mode = false
output_dir = "/tmp/tasks"
public_deal = true
verified_deal = true
fast_retrieval = true
skip_confirmation = false
generate_md5 = false
wallet = ""
max_price = "0"
start_epoch_hours = 96